apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-child-rbqd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-child-rbqd
    app.kubernetes.io/part-of: build-suite-component-update-hrkx
  name: multi-component-child-rbqd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-component-child-rbqd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-component-child-rbqd
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
